"""Query helpers for technical audit records."""

from __future__ import annotations

import uuid

from django.db.models import QuerySet

from apps.audit.models import AuditEvent, AuditEventType, AuditSession


def audit_event_types_active() -> QuerySet[AuditEventType]:
    """Return active audit event types ordered by code."""
    return AuditEventType.objects.filter(is_active=True).order_by("code")


def audit_events_for_entity(
    *,
    entity_type: str,
    entity_id: uuid.UUID | None = None,
) -> QuerySet[AuditEvent]:
    """Return audit events for an entity type and optional entity id."""
    queryset = AuditEvent.objects.filter(entity_type=entity_type)
    if entity_id is not None:
        queryset = queryset.filter(entity_id=entity_id)

    return queryset.select_related("actor", "event_type", "audit_session")


def audit_events_for_actor(*, actor_id: uuid.UUID) -> QuerySet[AuditEvent]:
    """Return audit events generated by an actor."""
    return AuditEvent.objects.filter(actor_id=actor_id).select_related(
        "event_type",
        "audit_session",
    )


def audit_sessions_for_actor(*, actor_id: uuid.UUID) -> QuerySet[AuditSession]:
    """Return audit sessions generated by an actor."""
    return AuditSession.objects.filter(actor_id=actor_id)
