# Generated by Django 5.2.15 on 2026-07-07 20:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
        ("reference_data", "0003_casetype_documenttype_statustype_workflowtype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("street", models.CharField(max_length=180)),
                ("number", models.CharField(blank=True, max_length=32)),
                ("complement", models.CharField(blank=True, max_length=120)),
                ("district", models.CharField(blank=True, max_length=120)),
                ("postal_code", models.CharField(blank=True, max_length=16)),
                ("notes", models.TextField(blank=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_addresses",
                        to="reference_data.city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_addresses",
                        to="reference_data.country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="customers.customer",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_addresses",
                        to="reference_data.state",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "customer address",
                "verbose_name_plural": "customer addresses",
                "ordering": ["customer__name", "-is_primary", "address_type", "street"],
                "indexes": [
                    models.Index(
                        fields=["customer", "address_type"],
                        name="customers_c_custome_7740eb_idx",
                    ),
                    models.Index(
                        fields=["customer", "is_primary"],
                        name="customers_c_custome_9a93f9_idx",
                    ),
                ],
            },
        ),
    ]
