# Generated by Django 5.2.15 on 2026-07-07 21:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.firearms.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0004_customer_address_customer_email_customer_phone_and_more"),
        ("reference_data", "0003_casetype_documenttype_statustype_workflowtype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Firearm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("serial_number", models.CharField(db_index=True, max_length=120)),
                (
                    "sinarm_registration",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("registration_valid_until", models.DateField(blank=True, null=True)),
                (
                    "craf_file",
                    models.FileField(
                        blank=True, upload_to=apps.firearms.models.craf_upload_to
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_archived",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "caliber",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_firearms",
                        to="reference_data.caliber",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="firearms",
                        to="customers.customer",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_firearms",
                        to="reference_data.manufacturer",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_firearms",
                        to="reference_data.firearmmodel",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "firearm",
                "verbose_name_plural": "firearms",
                "ordering": ["customer__name", "serial_number"],
                "indexes": [
                    models.Index(
                        fields=["customer", "status"],
                        name="firearms_fi_custome_a4b17d_idx",
                    ),
                    models.Index(
                        fields=["registration_valid_until"],
                        name="firearms_fi_registr_b9f4f4_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("serial_number",), name="ux_firearm_serial_number"
                    )
                ],
            },
        ),
    ]
